### ISSUE TITLE
Getting error after moving server

### ISSUE THREAD

**Issue by zeeshan4971** [Fitoussi/geo-my-wp#49]
Hey the plugin was working fine on the other server but when i moved it to the other server i am getting these errors in console.
![capture](https://cloud.githubusercontent.com/assets/11049979/16355944/37b9f31c-3ae1-11e6-8c48-2148dba12776.PNG)

Website link is http://www.foodgang.eu/search-products 
i also imported and exported the data from the old site and also changed some settings

**Comment by Fitoussi** [comment]
HI,
Since April of this year Google requires an API key in order to use its map services. This is true for sites that were created after the new rule came into effect. This is most likely the issue on your new site, the missing API key.

Please follow [this tutorial](http://docs.gravitygeolocation.com/article/101-create-google-map-api-key) on how to create the API key and how to enabled the API services. When done, enter the API key in GEP my WP Settings page.
