### ISSUE TITLE
no-results in theme folder not working

### ISSUE THREAD

**Issue by ChrisChiera** [Fitoussi/geo-my-wp#55]
Testing no results, entered "00000" and says "No Results Found". I'd like to edit the code of that no results template.

For search-forms and search-results, you simply copy those from the plugin into theme/geo-my-wp/posts/ and then in settings you choose the custom folder name. When copying "no-results" to that same folder changes to that file are not applied, and there appears to be no setting in the backend to choose the custom folder for no-results.

Is this a bug or working as expected for other users?

**Comment by Fitoussi** [comment]
Hello Chris,
Yes, I think this is a bug. However, this feature actually changed in GEO my WP 3.0. Since v3.0 the search-results template files also contains the "No results" message. 

In [this file](https://github.com/Fitoussi/geo-my-wp/blob/master/plugins/posts-locator/templates/search-results/gray/content.php) ( "gray" results template file ), as an example, you can see there is a check if locations ( posts ) found. And if so, it displays the loop. Otherwise, the "No results" message displays. Similar to how WordPress templates works.

My advice is to update to GEO my WP 3.0. It is still in beta, but beta 2.0 is pretty stable. And I hoping to officially release it by the new year, once I am done updating all of my extensions.

Just please make sure to read about the changes in v3.0 [here](http://geomywp.com/geo-my-wp-3-0/) ( beta 1 ) and [here](http://geomywp.com/geo-my-wp-3-0-beta-2/) ( beta 2 ). You can download beta 2 at the bottom of the page.

And if you do update, any feedback would be greatly appreciated.

**Comment by ChrisChiera** [comment]
Thanks for getting back so quickly and with all that helpful info. I'll give 3.0 b2 a whirl!

**Comment by ChrisChiera** [comment]
I can confirm no results works now in 3.0 b2, and much easier. Thank you.
